[project]
name = "easy-deeplearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "some-package>=0.1",
    "torch>=2.14.0",
    "torchsummary>=1.5.1",
    "torchvision>=0.29.0",
]
